# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RECIPE-APP
  username: postgres
  password: derrick

test:
  <<: *default
  database: RECIPE-APP
  username: postgres
  password: derrick

production:
  <<: *default
  database: RECIPE-APP
  username: kayjeee
  password: derrick
  